;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
				View-back-to-mark
				anchored-transpose
				backward-sexp
				forward-sexp
				indent-for-tab-command
				kill-region
				select-symbol
				select-word
				swiper-isearch
				undefined
				))

(setq mc/cmds-to-run-once
      '(
				my-wgrep-finish-and-save-buffers
				with-editor-finish
				avy-goto-word-0
				counsel-M-x
				describe-key
				swiper-mc
				wgrep-change-to-wgrep-mode
				))
