;; Le style d'indentation de Haypo
;; Yeah, groovy Baby !

(c-add-style 
 "haypo" 
 (quote
  (
   ;; Indentation de base = 4 espaces
   (c-basic-offset . 4)
   (indent-tabs-mode . nil)
   (c-backslash-column . 48) 
   (c-cleanup-list scope-operator) 
   (c-comment-only-line-offset . 0) 
   (c-electric-pound-behavior) 
   (c-hanging-braces-alist 
    (brace-list-open) 
    (brace-entry-open) 
    (substatement-open after) 
    (block-close . c-snug-do-while) 
    (extern-lang-open after) 
    (inexpr-class-open after) 
    (inexpr-class-close before)) 
   (c-hanging-colons-alist) 
   (c-hanging-comment-starter-p . t) 
   (c-hanging-comment-ender-p . t) 
   (c-offsets-alist 
    (string . c-lineup-dont-change) 
    (c . c-lineup-C-comments) 
    (defun-open . 0) 
    (defun-close . 0) 
    (defun-block-intro . +) 
    (class-open . 0) 
    (class-close . 0) 
    (inline-open . +) 
    (inline-close . 0) 
    (func-decl-cont . +) 
    (knr-argdecl-intro . +) 
    (knr-argdecl . 0) 
    (topmost-intro . 0) 
    (topmost-intro-cont . 0) 
    (member-init-intro . +) 
    (member-init-cont . 0) 
    (inher-intro . +) 
    (inher-cont . c-lineup-multi-inher) 
    (block-open . 0) 
    (block-close . 0)
    (brace-list-open . 0)
    (brace-list-close . 0)
    (brace-list-intro . +)
    (brace-list-entry . 0)
    (brace-entry-open . 0)
    (statement . 0)
    (statement-cont . +)
    (statement-block-intro . +)
    (statement-case-intro . +)
    (statement-case-open . 0)
    (substatement . +)

    ;; Pas de décalage lors de l'ouverture d'un bloc
    (substatement-open . 0)
    (case-label . 4)
    (access-label . -)
    (label . 20)
    (do-while-closure . 0)
    (else-clause . 0)
    (catch-clause . 0)
    (comment-intro . c-lineup-comment)
    (arglist-intro . +)
    (arglist-cont . 0)
    (arglist-cont-nonempty . c-lineup-arglist)
    (arglist-close . +)
    (stream-op . c-lineup-streamop)
    (inclass . +)
    (cpp-macro . -1000)
    (cpp-macro-cont . c-lineup-dont-change)
    (friend . 0)
    (objc-method-intro . -1000)
    (objc-method-args-cont . c-lineup-ObjC-method-args)
    (objc-method-call-cont . c-lineup-ObjC-method-call)
    (extern-lang-open . 0)
    (extern-lang-close . 0)
    (inextern-lang . +)
    (namespace-open . 0)
    (namespace-close . 0)
    (innamespace . +)
    (template-args-cont . +)
    (inlambda . c-lineup-inexpr-block)
    (lambda-intro-cont . +)
    (inexpr-statement . 0)
    (inexpr-class . +)
    )
   )
  )
 )
