(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(auth-source-save-behavior nil)
 '(auto-image-file-mode t)
 '(auto-save-default nil)
 '(backup-directory-alist
	 '(("." . "/home/dionisos/personnelle/records_and_save/emacs_backups/")))
 '(backward-delete-char-untabify-method nil)
 '(calendar-day-header-array ["Di" "Lu" "Ma" "Me" "Je" "Ve" "Sa"])
 '(calendar-day-name-array
	 ["Dimanche" "Lundi" "Mardi" "Mercredi" "Jeudi" "Vendredi" "Samedi"])
 '(calendar-week-start-day 1)
 '(case-fold-search nil)
 '(column-number-mode t)
 '(current-language-environment "utf-8")
 '(delete-by-moving-to-trash t)
 '(delete-old-versions t)
 '(delete-selection-mode 1)
 '(doc-view-continuous t)
 '(electric-indent-mode nil)
 '(explicit-shell-file-name "/usr/bin/bash")
 '(find-file-visit-truename t)
 '(history-length 10000)
 '(ido-auto-merge-work-directories-length -1)
 '(ido-enable-regexp t)
 '(ido-mode 'both nil (ido))
 '(indent-tabs-mode t)
 '(inhibit-startup-screen t)
 '(kill-ring-max 100)
 '(line-move-visual t)
 '(line-number-mode t)
 '(minibuffer-prompt-properties '(read-only t cursor-intangible t face minibuffer-prompt))
 '(orderless-matching-styles '(orderless-regexp orderless-literal))
 '(org-agenda-include-diary t)
 '(org-agenda-restore-windows-after-quit t)
 '(org-agenda-window-setup 'current-window)
 '(org-closed-keep-when-no-todo nil)
 '(org-columns-default-format "%TODO %ITEM %Effort{:}")
 '(org-log-done nil)
 '(org-log-repeat nil)
 '(org-startup-truncated nil)
 '(org-tags-column 100)
 '(org-tags-exclude-from-inheritance '("ORDERED"))
 '(org-timer-default-timer "4")
 '(org-track-ordered-property-with-tag t)
 '(package-selected-packages
	 '(flyspell-correct yasnippet xonsh-mode which-key wgrep w3m vertico use-package-chords undo-tree spray selectrum realgud ranger popup phi-search org-roam orderless openwith multiple-cursors markdown-mode marginalia magit langtool kiwix hydra google-translate flycheck embark-consult emacsql-sqlite3 company-statistics company-quickhelp avy all-the-icons-dired abyss-theme))
 '(printer-name "EPSON_WF-2750")
 '(register-preview-delay nil)
 '(savehist-mode t)
 '(scroll-conservatively 99)
 '(scroll-step 1)
 '(select-enable-clipboard t)
 '(show-paren-mode t)
 '(show-trailing-whitespace t)
 '(split-window-preferred-function '(lambda (window) (nil)))
 '(standard-indent 2)
 '(tab-width 2)
 '(tool-bar-mode nil)
 '(transient-mark-mode t)
 '(trash-directory "/home/dionisos/.local/share/Trash/files")
 '(truncate-lines nil)
 '(use-package-hook-name-suffix nil)
 '(version-control t)
 '(visible-bell t)
 '(yank-excluded-properties t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
