(defun my-estimate-weighted-time ()
  "Estimate a weighted duration based on selected time ranges and user-provided coefficients."
  (interactive)
  (let ((lines (split-string (buffer-substring-no-properties (region-beginning) (region-end)) "\n" t))
        (total 0))
    (dolist (line lines)
      (when (string-match "^\\([0-9]+\\)h\\([0-9]+\\)-\\([0-9]+\\)h\\([0-9]+\\):" line)
        (let* ((h1 (string-to-number (match-string 1 line)))
               (m1 (string-to-number (match-string 2 line)))
               (h2 (string-to-number (match-string 3 line)))
               (m2 (string-to-number (match-string 4 line)))
               (start (+ (* h1 60) m1))
               (end (+ (* h2 60) m2))
               (duration (if (<= end start)
                             (+ (- end start) 1440) ;; handle day wrap
                           (- end start)))
               (coef (read-number (format "Duration: %d minutes for: \"%s\". Weight (0–1)? " duration line))))
          (setq total (+ total (* duration coef))))))
    (message "⏱ Estimated total time: %.0f minutes" total)))
